### ISSUE TITLE
Is rag Linux only? Error on Mac M2

### ISSUE THREAD

**Issue by awaescher** [neuml/rag#1]
This looks very promising and comes with a great timing as I was checking txtai and graphrag over the last few days.
However, I can't run in on my Mac M2 Pro as it says:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
6626dfa8e7ac3227b9472397e88bd3fa20b0a35e1686ec8892f09d3efe4273b5
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Is there (planned) support for non-Linux systems?

**Comment by davidmezzetti** [comment]
Hello. I can build arm64 images like I do for the base txtai projects.

**Comment by awaescher** [comment]
Would love to try it

**Comment by davidmezzetti** [comment]
Added to v0.2.0 builds.
